[project]
name = "osmlocation3d"
version = "0.1.0"
description = "Generate 3D location meshes from OSM data and DEM terrain files"
readme = "README.md"
authors = [
    { name = "Rita-Barco", email = "rita.barco@tecnico.ulisboa.pt" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "osmnx>=2.0.7",
    "pyproj>=3.7.1",
    "pyvista>=0.49.0",
    "pyyaml>=6.0.3",
    "rasterio>=1.4.4",
    "shapely>=2.1.2",
    "trimesh>=5.1.0",
]

[project.scripts]
osmlocation3d = "osmlocation3d:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
